
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox4;
	
	private global::Gtk.ComboBox cmbOne;
	
	private global::Gtk.Button btnTwo;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.cmbOne = global::Gtk.ComboBox.NewText ();
		this.cmbOne.Name = "cmbOne";
		this.vbox4.Add (this.cmbOne);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.cmbOne]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.btnTwo = new global::Gtk.Button ();
		this.btnTwo.CanFocus = true;
		this.btnTwo.Events = ((global::Gdk.EventMask)(768));
		this.btnTwo.Name = "btnTwo";
		this.btnTwo.UseUnderline = true;
		this.btnTwo.Label = global::Mono.Unix.Catalog.GetString ("_OK");
		this.vbox4.Add (this.btnTwo);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.btnTwo]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		this.Add (this.vbox4);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
